version: '3.2'

services:
    app:
        build: php-fpm
        container_name: php-fpm
        working_dir: /var/www/html
        ports:
            - ${PHP_FPM_PORT}:9000
        environment:
            - XDEBUG_REMOTE_ENABLE=${XDEBUG_REMOTE_ENABLE}
            - XDEBUG_CONNECT_BACK=${XDEBUG_CONNECT_BACK}
            - XDEBUG_IDEKEY=${XDEBUG_IDEKEY}
            - XDEBUG_PORT=${XDEBUG_PORT}
            - XDEBUG_REMOTE_HOST=${SERVER_NAME}
        links:
            - db
        depends_on:
            - db
            - composer
        volumes:
            - ${APP_PATH}:/var/www/html
    composer:
        image: composer
        container_name: composer
        user: "1000"
        working_dir: /
        volumes:
            - ${APP_PATH}:/
        command: >
          bash -c "composer install &&
                   ./vendor/bin/simple-phpunit --version"
#    node:
#        image: node:8
#        container_name: node
#        user: "1000"
#        working_dir: /
#        volumes:
#            - ${APP_PATH}:/
#        command: >
#          bash -c "npm cache clean --force &&
#                   npm install &&
#                   npm run dev &&
#                   npm run watch"
    nginx:
        image: nginx:alpine
        container_name: nginx
        working_dir: /var/www/
        ports:
            - ${APP_PORT}:80
        links:
            - app
        volumes:
            - ${APP_PATH}:/var/www/html
            - ./nginx/config/default.conf:/etc/nginx/conf.d/default.conf
            - ./nginx/config/nginx.conf:/etc/nginx/nginx.conf
            - ./logs/nginx/:/var/log/nginx
    mysql:
        image: mysql:5.7
        container_name: mysql
        ports:
            - ${MYSQL_PORT}:3306
        environment:
            MYSQL_DATABASE: ${DATABASE_NAME}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        volumes:
           - ./db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
           - ./db/config/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
           - ./data/mysql_data:/var/lib/mysql